apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: searchplatform

commonLabels:
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - searcher-deployment.yaml
  - searcher-service.yaml